version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: keycloak-postgres
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: supersecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Optional: Expose PostgreSQL port if you need to access it directly
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak_user -d keycloak"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:25.0.0
    container_name: keycloak
    environment:
      # Database connection settings
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: supersecretpassword
      # Keycloak admin user
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: adminpassword
      # Hostname settings
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HTTP_ENABLED: "true" # Enable HTTP for local development, use HTTPS in production
      # Production mode (recommended)
      KC_FEATURES: web_authn,token_exchange,client_policies,admin_fine_grained_authz,declarative_user_profile,scripts,docker
      KC_HEALTH_ENABLED: "true" # Enable health endpoints
      KC_METRICS_ENABLED: "true" # Enable metrics endpoints
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    depends_on:
      postgres:
        condition: service_healthy # Ensure PostgreSQL is healthy before starting Keycloak
    command:
      - start-dev # Use 'start' for production, 'start-dev' for development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/realms/master"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  keycloak_data:
